### ISSUE TITLE
 python3 gen_biquad_filter_s32.py abc.csv , cmd failed to run.

### ISSUE THREAD

**Issue by jian-yuan-cmd** [xmos/lib_xcore_math#200]
In the development of EQ effects, I need to use Python tools to generate. c and. h files based on CSV files.
However, I can't  generate the . h and. c files here. The details are as follows:

yuanjian@YuanJians-MacBook-Air-3 python % 
yuanjian@YuanJians-MacBook-Air-3 python % pip3 --version
pip 24.1.2 from /Users/yuanjian/Library/Python/3.9/lib/python/site-packages/pip (python 3.9)
yuanjian@YuanJians-MacBook-Air-3 python % 
yuanjian@YuanJians-MacBook-Air-3 python % python3 --version
Python 3.9.6
yuanjian@YuanJians-MacBook-Air-3 python % 
yuanjian@YuanJians-MacBook-Air-3 python % cat abc.csv 
0.002550533475062201, 0.005101066950124402, 0.002550533475062201, 1.8521452628914687, -0.8623473967917175%                                                   yuanjian@YuanJians-MacBook-Air-3 python % 
yuanjian@YuanJians-MacBook-Air-3 python % python3 gen_biquad_filter_s32.py abc.csv 
Traceback (most recent call last):
  File "/Users/yuanjian/workspace/0_xmos/000_confidential/3600/XVF3600_100_dsp_single_core_no_mic_algorithm/lib_xcore_math/lib_xcore_math/jian1117Download/lib_xcore_math/lib_xcore_math/python/gen_biquad_filter_s32.py", line 183, in <module>
    main()
  File "/Users/yuanjian/workspace/0_xmos/000_confidential/3600/XVF3600_100_dsp_single_core_no_mic_algorithm/lib_xcore_math/lib_xcore_math/jian1117Download/lib_xcore_math/lib_xcore_math/python/gen_biquad_filter_s32.py", line 61, in main
    args = extra_process_args(parser.parse_args())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/argparse.py", line 1818, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/argparse.py", line 1851, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/argparse.py", line 2063, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/argparse.py", line 2019, in consume_positionals
    take_action(action, args)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/argparse.py", line 1912, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/argparse.py", line 2443, in _get_values
    value = self._get_value(action, arg_string)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/argparse.py", line 2476, in _get_value
    result = type_func(arg_string)
  File "/Users/yuanjian/workspace/0_xmos/000_confidential/3600/XVF3600_100_dsp_single_core_no_mic_algorithm/lib_xcore_math/lib_xcore_math/jian1117Download/lib_xcore_math/lib_xcore_math/python/xmath_script.py", line 46, in filter_id
    **assert( filter_name_pattern.match(fname) is not None )**
AssertionError
yuanjian@YuanJians-MacBook-Air-3 python % 
yuanjian@YuanJians-MacBook-Air-3 python %

**Comment by ACascarino** [comment]
Hi @jian-yuan-cmd,

You must also include a filter name when running this script:
`python3 gen_biquad_filter_s32.py [desired name of filter] [coefficients]`

This will then generate `[desired name of filter].c` and `desired name of filter.h`, which will declare and define a function `[desired name of filter](int32_t new_sample)`.


You should be able to do
`python3 gen_biquad_filter_s32.py --help`
for more information.

Kind regards,
Angel Cascarino,
Software Engineer, XMOS

**Comment by jian-yuan-cmd** [comment]
Hi,  Angel , thanks.
My command is missing the file name parameter, it's okay now.
yuanjian@YuanJians-MacBook-Air-4 script % python3 gen_biquad_filter_s32.py lowpass_176khz_fc27khz lowpass_176khz_fc27khz.csv 
Filter section count: 1
Files to be written:
  ./lowpass_176khz_fc27khz.h
  ./lowpass_176khz_fc27khz.c

************************************************
Best regard.
jian Yuan
